App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^cart/$', views.cart,name='cart'),
    url(r'^entry/$', views.entry,name='entry'),
    url(r'^logout/$', views.logout,name='logout'),
    url(r'^detail.html/(\d+)$', views.detail, name='detail'),
    url(r'^register/$', views.register,name='register'),
    url(r'^getjson/$', views.getjson),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^islogin/$', views.islogin, name='islogin'),
    url(r'^cartadd/$', views.cartadd, name='cartadd'),
    url(r'^cartsub/$', views.cartsub, name='cartsub'),
    url(r'^delgoods/$', views.delgoods, name='delgoods'),
    url(r'^changecartstatus/$', views.changecartstatus, name='changecartstatus'),
    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),
    url(r'^generateorder/$', views.generateorder, name='generateorder'),
    url(r'^orderinfo/(\d+)/$', views.orderinfo, name='orderinfo'),



]

JLG/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('App.urls',namespace='App'))
]

App/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=80)
    password = models.CharField(max_length=256)
    token = models.CharField(max_length=256,default='')

class Index_Img(models.Model):
    use = models.CharField(max_length=100)
    num = models.CharField(max_length=20,default='')
    src = models.CharField(max_length=256,default='')
    time = models.CharField(max_length=40,default='')
    describe = models.CharField(max_length=256,default='')
    price = models.CharField(max_length=40,default='')
    salesVolume = models.CharField(max_length=100,default='')


class detail_json(models.Model):
    num = models.CharField(max_length=8,default='')
    path = models.CharField(max_length=100,default='')
    TV = models.CharField(max_length=20,default='')
    number = models.CharField(max_length=50,default='')
    youHui = models.CharField(max_length=100,default='')
    jiFen = models.CharField(max_length=50,default='')
    smallimg = models.CharField(max_length=256,default='')
    img = models.CharField(max_length=100,default='')
    descibe = models.CharField(max_length=256,default='')
    price = models.DecimalField(max_digits=7,decimal_places=2,default='')
    introduce = models.TextField(default='')
    collocation = models.TextField(default='')


class Cart(models.Model):
    user = models.ForeignKey(User)
    goods = models.ForeignKey(detail_json)
    number = models.IntegerField()
    isselect = models.BooleanField(default=True)


class Order(models.Model):
    user = models.ForeignKey(User)
    createtime = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(default=1)
    identifier = models.CharField(max_length=256)


class OrderGoods(models.Model):
    order = models.ForeignKey(Order)
    goods = models.ForeignKey(detail_json)
    number = models.IntegerField(default=1)

templates/cart.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>购物车</title>
    <link rel="shortcut icon" href="{% static '/img/title.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/css/cart.css' %}"/>
    <script src="{% static '/js/jquery-1.12.0.js' %}"></script>
    <script src="{% static '/js/jquery.cookie.js' %}"></script>
    {#		<script src="{% static '/js/cart.js' %}"></script>#}
    <script src="{% static '/js/mycart.js' %}"></script>

</head>
<body>
<div id="top">
    <div id="top_left">
        <img src="{% static '/img/ind-tel.png' %}">
        <span>电话热线<b>400-630-0077</b></span>
    </div>
    <div id="top_center">
        {% if username %}
            <span>您好,{{ username }} <a href="{% url 'App:logout' %}"> [退出]</a></span>
        {% else %}
            <a href="{% url 'App:entry' %}">[登录]</a>
            <a href="{% url 'App:register' %}">[免费注册]</a>
        {% endif %}
    </div>
    <ul id="top_right">
        <a href="#">
            <li>我的嘉</li>
        </a>
        <a href="#">
            <li>我的订单</li>
        </a>
        <a href="#">
            <li>客户服务</li>
        </a>
        <a href="#">
            <li>电视会员激活</li>
        </a>
        <a href="#">
            <li>
                <img src="{% static '/img/ind-mobile.png' %}">
                <span>手机嘉丽购</span>
            </li>
        </a>
    </ul>
</div>
<div id="logo">
    <div id="logo_left">
        <a href="{% url 'App:index' %}"><img src="{% static '/img/ladygood.png' %}"></a>
    </div>
    <div id="logo_center">购物车</div>
    <div id="logo_right">
        <ul>
            <li>
                <span style="background: #e81355;"></span>
                <div></div>
                <label>我的购物车</label>
            </li>
            <li>
                <span></span>
                <div></div>
                <label>提交订单</label>
            </li>
            <li>
                <span></span>
                <div></div>
                <label>等待付款</label>
            </li>
            <li>
                <span></span>
                <div></div>
                <label>支付成功</label>
            </li>
        </ul>
    </div>
</div>
<div id="cart">
    <div class="cart_top">
        <span>全部商品</span>
        <a href="{% url 'App:index' %}">返回首页</a>
    </div>
    <div class="cart_yes">
        <table>
            <thead>
            <tr>
                <th>全选</th>
                <th>商品名</th>
                <th>单价（元）</th>
                <th>数量</th>
                <th>嘉丽价</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for cart in carts %}
                <tr class="goods">
                    <td class="td1" isselect="{{ cart.isselect }}">
                        {% if cart.isselect %}
                            <span class="check ok" cartid="{{ cart.id }}">√</span>
                        {% else %}
                            <span class="noCheck ok" cartid="{{ cart.id }}">√</span>
                        {% endif %}
                        <img src="{{ cart.goods.img }}" alt="" id="5" style="cursor: pointer;">
                    </td>
                    <td class="td1">
                        <a href="#">
                            <h5>{{ cart.goods.descibe }}</h5>
                        </a>
                        <span>{{ cart.goods.number }}</span>
                        <span class="youHui">
                                        减
                                    </span>
                        <span class="TV">
                                        TV
                                    </span>
                        <p style="color: rgb(235, 22, 86);">
                            {{ cart.goods.youHui }}
                        </p>
                    </td>
                    <td class="td2" price="{{ cart.goods.price }}">¥{{ cart.goods.price }}</td>
                    <td class="td2 num">
                        <div class="minus" goodsid="{{ cart.goods.num }}">-</div>
                        <input type="text" readonly="readonly" class="goodnum" value="{{ cart.number }}">
                        <div class="plus" goodsid="{{ cart.goods.num }}">+</div>
                    </td>
                    <td class="td2 cart_price" jl_price="{{ cart.goods.price }}"></td>
                    <td class="td2">
                        <p>
                            <a href="#">加入收藏夹</a>
                        </p>
                        <p>
                            <a href="#" class="del" goodsid="{{ cart.goods.num }}">删除</a>
                        </p>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="cart_yes_settlement">
            <div class="settlement_left">
						<span>
							<input type="checkbox" style="outline: none;" id="checked" isselect="false">
							<label for="checked" style="margin-left: -5px;">全选</label>
						</span>
            </div>
            <div class="settlement_center">
                <p>商品金额：<span class="jinE"></span>元</p>
                <p>运费：<span class="yunFei">10.00</span>元</p>
                <p>可返积分：<span class="jiFen">512</span></p>
                <p style="color: #e21357; font-weight: bold;">总计：<span class="zje"></span>元</p>
            </div>
            <div class="settlement_right">
                <input type="button" value="去结算">
            </div>
        </div>
    </div>
</div>
<div id="GYLike">
    <span>猜你喜欢</span>
    <div class="GYLike_all">
        <div class="GYLike_one">
            <img src="{{ ind1.src }}" alt="">
            <a href="{% url 'App:detail' ind1.salesVolume %}"><p
                    class="GYLike_describe describe">{{ ind1.describe }}</p></a>
            <p class="GYLike_price">{{ ind1.price }}</p>
        </div>
        <div class="GYLike_one">
            <img src="{{ ind2.src }}" alt="">
            <a href="{% url 'App:detail' ind2.salesVolume %}"><p
                    class="GYLike_describe describe">{{ ind2.describe }}</p></a>
            <p class="GYLike_price">{{ ind2.price }}</p>
        </div>
        <div class="GYLike_one">
            <img src="{{ ind3.src }}" alt="">
            <a href="{% url 'App:detail' ind3.salesVolume %}"><p
                    class="GYLike_describe describe">{{ ind3.describe }}</p></a>
            <p class="GYLike_price">{{ ind3.price }}</p>
        </div>
        <div class="GYLike_one">
            <img src="{{ ind4.src }}" alt="">
            <a href="{% url 'App:detail' ind4.salesVolume %}"><p
                    class="GYLike_describe describe">{{ ind4.describe }}</p></a>
            <p class="GYLike_price">{{ ind4.price }}</p>
        </div>
        <div class="GYLike_one">
            <img src="{{ ind5.src }}" alt="">
            <a href="{% url 'App:detail' ind5.salesVolume %}"><p
                    class="GYLike_describe describe">{{ ind5.describe }}</p></a>
            <p class="GYLike_price">{{ ind5.price }}</p>
        </div>
    </div>
</div>
<div id="service">
    <div class="service_top"></div>
    <div class="service_bottom">
        <div class="QRCode"></div>
        <div class="service_list">
            <dl>
                <dt>购物指南</dt>
                <a href="#">
                    <dd>新用户注册/激活</dd>
                </a>
                <a href="#">
                    <dd>如何订购</dd>
                </a>
                <a href="#">
                    <dd>常见问题</dd>
                </a>
            </dl>
            <dl>
                <dt>会员中心</dt>
                <a href="#">
                    <dd>会员权益</dd>
                </a>
                <a href="#">
                    <dd>美丽积分</dd>
                </a>
                <a href="#">
                    <dd>订单查询</dd>
                </a>
                <a href="#">
                    <dd>找回密码</dd>
                </a>
            </dl>
            <dl>
                <dt>配送服务</dt>
                <a href="#">
                    <dd>物流跟踪</dd>
                </a>
                <a href="#">
                    <dd>免运费政策</dd>
                </a>
            </dl>
            <dl>
                <dt>支付说明</dt>
                <a href="#">
                    <dd>货到付款</dd>
                </a>
                <a href="#">
                    <dd>在线支付</dd>
                </a>
            </dl>
            <dl>
                <dt>售后服务</dt>
                <a href="#">
                    <dd>退换货政策</dd>
                </a>
                <a href="#">
                    <dd>退换货流程</dd>
                </a>
                <a href="#">
                    <dd>安全与保密</dd>
                </a>
            </dl>
        </div>
        <div class="telephone"></div>
    </div>
</div>
<div id="bottom">
    <ul class="bottom_link">
        <li><a href="#">商城首页</a></li>
        <li><a href="#">官网首页</a></li>
        <li><a href="#">供应商登录</a></li>
        <li><a href="#">供货联系</a></li>
        <li><a href="#">收藏我们</a></li>
        <li><a href="#">公司简介</a></li>
        <li><a href="#">媒体报道</a></li>
        <li><a href="#">嘉丽购招聘</a></li>
        <li><a href="#">官方微博</a></li>
        <li style="border-right: none;"><a href="#">合作网站：范游网</a></li>
    </ul>
    <p>嘉丽购物有限责任公司 Copyright 2010-2014 jialigou.All Rights Reserved</p>
    <p>国家广电总局批号：广局[2010] 278号湘ICP备10203162号-3</p>
    <a href="#"><img src="{% static '/img/pic.gif' %}" title="站长统计" class="pic"></a>
    <ul class="bottom_security">
        <li class="first"><img src="{% static '/img/kx.jpg' %}"></li>
        <li><a href="#"><img src="{% static '/img/360.jpg' %}"></a></li>
        <li><img src="{% static '/img/alipay_s.gif' %}"></li>
        <li><a href="#"><img src="{% static '/img/hn110_s.gif' %}"></a></li>
    </ul>
</div>
</body>
</html>

templates/detail.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>商品详情</title>
		<link rel="shortcut icon" href="{% static '/img/title.ico' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static '/css/detail.css' %}"/>
		<script src="{% static '/js/jquery-1.12.0.js' %}"></script>
		<script src="{% static '/js/jquery.cookie.js' %}"></script>
{#		<script src="{% static '/js/detail.js' %}"></script>#}
        <script src="{% static '/js/mydetail.js' %}"></script>

	</head>
	<body>
        <div id="top">
			<div id="top_left">
				<img src="{% static '/img/ind-tel.png' %}">
				<span>电话热线<b>400-630-0077</b></span>
			</div>
			<div id="top_center">
				{% if username %}
                    <span>您好,{{ username }} <a href="{% url 'App:logout' %}"> [退出]</a></span>
                {% else %}
				    <a href="{% url 'App:entry' %}">[登录]</a>
				    <a href="{% url 'App:register' %}">[免费注册]</a>
                {% endif %}
			</div>
		<ul id="top_right">
				<a href="#"><li>我的嘉</li></a>
				<a href="#"><li>我的订单</li></a>
				<a href="#"><li>客户服务</li></a>
				<a href="#"><li>电视会员激活</li></a>
				<a href="#"><li>
					<img src="{% static '/img/ind-mobile.png' %}">
					<span>手机嘉丽购</span>
				</li></a>
			</ul>
		</div>
		<div id="logo">
			<div id="logo_left">
				<a href="{% url 'App:index' %}"><img src="{% static '/img/ladygood.png' %}"></a>
			</div>
			<div id="logo_center">
				<input type="text" placeholder="输入商品名称或电视商品编号">
				<span id="search">
					<i></i>
					<span>搜索</span>
				</span>
			</div>
			<div id="logo_right">
				<span class="red">{{ all_cart }}</span>
				<span class="span2">我的购物车</span>
			</div>
		</div>
		<div id="nav">
			<div id="nav_left">全部商品分类</div>
			<ul id="nav_list">
				<li><a href="#">护肤、化妆、美容</a></li>
				<li><a href="#">箱包、服饰、配饰</a></li>
				<li><a href="#">珠宝、收藏品</a></li>
				<li><a href="#">家居、厨房、日用</a></li>
				<li><a href="#">电脑、数码、家电</a></li>
				<li><a href="#">运动、健康、保健</a></li>
			</ul>
			<ul id="nav_center">
				<li>
					<span style="color: #e91456;"><a href="{% url 'App:index' %}">首页</a></span>
					<i>|</i>
				</li>
				<li>
					<span><a href="http://www.jialigou.com/tv/live.html">TV直播</a></span>
					<i>|</i>
				</li>
				<li>
					<span><a href="http://www.jialigou.com/topic/topic/topic_id/8">嘉丽全球购</a></span>
					<i>|</i>
				</li>
				<li>
					<span><a href="http://www.jialigou.com/jhx/index.html">水果生鲜</a></span>
					<i>|</i>
				</li>
			</ul>
			<div id="nav_right">
				<span>订购热线</span>
				<span style="color: #e91456;">400-630-0077</span>
			</div>
		</div>
		<div id="goods">
			<div id="goods_path">
                <a href="#" class="path_1">{{ path1 }}</a>
                <i>></i>
                <a href="#" class="path_2">{{ path2 }}</a>
                <i>></i>
                <a href="#" class="path_3">{{ path3 }}</a>
            </div>
			<div id="goods_details">
				<div class="details_bigimg">
					<div class="smallArea"></div>
                    <img src="{{ det.img }}" alt="">
				</div>
				<div class="bigArea">
                    <img src="{{ det.img }}" alt="" class="bigArea_bigImg">
                </div>
				<div class="details_information">
					<div class="title">
                        <i>{{ det.TV }}</i>
                        <b>{{ det.descibe }}</b>
                        <span>{{ det.number }}</span>
                    </div>
					<div class="price">
						<p class="price_top">
							<label>嘉丽价</label>
                            <b>
                                ¥
                                <span>{{ det.price }}</span>
                            </b>
						</p>
						<p class="price_center">
							<label>促销优惠</label>
                            <span>{{ yh1 }}</span>
                            <span class="newline">{{ yh2 }}</span>
						</p>
						<p class="price_bottom">
							<label>积分</label>
                            <span>{{ det.jiFen }}</span>
						</p>
					</div>
					<div class="standard">
						<div class="size">
							<label>尺寸</label>
                            <span >暂无尺寸</span>
						</div>
						<div class="color">
							<label>颜色</label>
                            <span>颜色</span>
						</div>
					</div>
					<div class="number">
						<label>数量</label>
						<div class="minus">-</div>
						<input type="text" value="1" class="goodnum">
						<div class="plus">+</div>
						<span>件</span>
					</div>
					<div class="settlement">
						<span class="btn1">立即购买</span>
						<span class="btn2" goodsid="{{ det.num }}" number="{{ det.num }}">加入购物车</span>
						<span class="btn3">收藏</span>
					</div>
				</div>
				<div class="details_smallImg">
                    <img src="{{ det.img }}" alt="">
                </div>
			</div>
		</div>
		<div id="share">
			<span>分享到：</span>
			<a href="#" class="weixin" title="分享到微信"></a>
			<a href="#" class="qq" title="分享到QQ空间"></a>
			<a href="#" class="sina" title="分享到新浪微博"></a>
			<a href="#" class="tenxun" title="分享到腾讯微博"></a>
			<a href="#" class="genduo"></a>
			<div class="qita"></div>
		</div>
		<div id="collocation">
			<span>最佳搭配</span>
			<div class="collocation_all">
                <div class="collocation_one">
                    <img src="{{ ind2.src }}" alt="">
                    <p class="collocation_describe describe">{{ ind2.describe }}</p>
                    <p class="collocation_price">{{ ind2.price }}</p>
                </div>
                <div class="collocation_one">
                    <img src="{{ ind3.src }}" alt="">
                    <p class="collocation_describe describe">{{ ind3.describe }}</p>
                    <p class="collocation_price">{{ ind3.price }}</p>
                </div>
                <div class="collocation_one">
                    <img src="{{ ind4.src }}" alt="">
                    <p class="collocation_describe describe">{{ ind4.describe }}</p>
                    <p class="collocation_price">{{ ind4.price }}</p>
                </div>
                <div class="collocation_one">
                    <img src="{{ ind5.src }}" alt="">
                    <p class="collocation_describe describe">{{ ind5.describe }}</p>
                    <p class="collocation_price">{{ ind5.price }}</p>
                </div>
            </div>
		</div>
		<div id="parameter">
			<div id="parameter_left">
				<div id="RBrowse">
					<p class="browse">最近浏览</p>
                    <div class="RBrowse_one">
                        <img src="{{ ind2.src }}" alt="">
                        <a href="{% url 'App:detail' ind2.salesVolume %}"><p class="RBrowse_describe describe">{{ ind2.describe }}</p></a>
                        <p class="RBrowse_price">{{ ind2.price }}</p>
                    </div>
                    <div class="RBrowse_one">
                        <img src="{{ ind3.src }}" alt="">
                        <a href="{% url 'App:detail' ind3.salesVolume %}"><p class="RBrowse_describe describe">{{ ind3.describe }}</p></a>
                        <p class="RBrowse_price">{{ ind3.price }}</p>
                    </div>
				</div>
				<div id="sell">
					<p class="sell_p">热销排行</p>
                    <div class="sell_one">
                        <img src="{{ ind4.src }}" alt="">
                        <a href="{% url 'App:detail' ind4.salesVolume %}"><p class="sell_describe describe">{{ ind4.describe }}</p></a>
                        <p class="sell_price">{{ ind4.price }}</p>
                    </div>
                    <div class="sell_one">
                        <img src="{{ ind5.src }}" alt="">
                        <a href="{% url 'App:detail' ind5.salesVolume %}"><p class="sell_describe describe">{{ ind5.describe }}</p></a>
                        <p class="sell_price">{{ ind5.price }}</p>
                    </div>
				</div>
			</div>
			<div id="introduce">
				<ul class="intr_top">
					<li>
						<i id="red"></i>
						<p>商品介绍</p>
					</li>
					<li>
						<i></i>
						<p>商品参数</p>
					</li>
					<li>
						<i></i>
						<p>包装清单</p>
					</li>
					<li>
						<i></i>
						<p>商品评论</p>
					</li>
					<li>
						<i></i>
						<p>用户咨询</p>
					</li>
				</ul>
				<ul class="intr_bottom">
                    <li>
                        <img src="{{ in1 }}" alt="">
                    </li>
                    <li>
                        <img src="{{ in2 }}" alt="">
                    </li>
                    <li>
                        <img src="{{ in3 }}" alt="">
                    </li>
                    <li>
                        <img src="{{ in4 }}" alt="">
                    </li>
                    <li>
                        <img src="{{ in5 }}" alt="">
                    </li>
                </ul>
			</div>
		</div>
		<div id="service">
			<div class="service_top"></div>
			<div class="service_bottom">
				<div class="QRCode"></div>
				<div class="service_list">
					<dl>
						<dt>购物指南</dt>
						<a href="#"><dd>新用户注册/激活</dd></a>
						<a href="#"><dd>如何订购</dd></a>
						<a href="#"><dd>常见问题</dd></a>
					</dl>
					<dl>
						<dt>会员中心</dt>
						<a href="#"><dd>会员权益</dd></a>
						<a href="#"><dd>美丽积分</dd></a>
						<a href="#"><dd>订单查询</dd></a>
						<a href="#"><dd>找回密码</dd></a>
					</dl>
					<dl>
						<dt>配送服务</dt>
						<a href="#"><dd>物流跟踪</dd></a>
						<a href="#"><dd>免运费政策</dd></a>
					</dl>
					<dl>
						<dt>支付说明</dt>
						<a href="#"><dd>货到付款</dd></a>
						<a href="#"><dd>在线支付</dd></a>
					</dl>
					<dl>
						<dt>售后服务</dt>
						<a href="#"><dd>退换货政策</dd></a>
						<a href="#"><dd>退换货流程</dd></a>
						<a href="#"><dd>安全与保密</dd></a>
					</dl>
				</div>
				<div class="telephone"></div>
			</div>
		</div>
		<div id="bottom">
			<ul class="bottom_link">
				<li><a href="#">商城首页</a></li>
				<li><a href="#">官网首页</a></li>
				<li><a href="#">供应商登录</a></li>
				<li><a href="#">供货联系</a></li>
				<li><a href="#">收藏我们</a></li>
				<li><a href="#">公司简介</a></li>
				<li><a href="#">媒体报道</a></li>
				<li><a href="#">嘉丽购招聘</a></li>
				<li><a href="#">官方微博</a></li>
				<li style="border-right: none;"><a href="#">合作网站：范游网</a></li>
			</ul>
			<p>嘉丽购物有限责任公司 Copyright 2010-2014 jialigou.All Rights Reserved</p>
			<p>国家广电总局批号：广局[2010] 278号湘ICP备10203162号-3</p>
			<a href="#"><img src="{% static '/img/pic.gif' %}" title="站长统计" class="pic"></a>
			<ul class="bottom_security">
				<li class="first"><img src="{% static '/img/kx.jpg' %}"></li>
				<li><a href="#"><img src="{% static '/img/360.jpg' %}"></a></li>
				<li><img src="{% static '/img/alipay_s.gif' %}"></li>
				<li><a href="#"><img src="{% static '/img/hn110_s.gif' %}"></a></li>
			</ul>
		</div>
    </body>
</html>

templates/entry.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>用户登录</title>
		<link rel="shortcut icon" href="{% static '/img/title.ico' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static '/css/entry.css' %}"/>
		<script src="{% static '/js/jquery-1.12.0.js' %}"></script>
		<script src="{% static '/js/jquery.cookie.js' %}"></script>
{#		<script src="{% static '/js/entry.js' %}"></script>#}
        <script src="{% static '/js/verifycode.js' %}"></script>

	</head>
	<body>
        <div id="logo">
			<div id="logo_left">
				<a href="{% url 'App:index' %}"><img src="{% static '/img/ladygood.png' %}"></a>
			</div>
			<div id="logo_center">用户登录</div>
			<div id="logo_right">
				<a href="#">嘉丽购电视会员激活入口</a>
			</div>
		</div>
		<div id="entry">
			<div class="entry_left">
				<img src="{% static '/img/denglu.png' %}">
			</div>
			<div class="entry_right">
				<p class="entry_right_title">
					<span>嘉丽购会员登录</span>
					<a href="{% url 'App:register' %}">免费注册</a>
				</p>
				<form method="post">
                    {% csrf_token %}
					<input type="text" placeholder="用户名/电话号码" class="input1" name="username">
					<input type="password" placeholder="密码" class="input1" name="password">
					<p class="clear">
						<input type="text" placeholder="验证码" class="input2">
						<span class="verCode"></span>
					</p>
                    <p style="border-bottom: 10px">
                        <b style="font-size: 15px; color: red; border-bottom: 10px">{{ error }}</b>
                    </p>
                    <br>
					<p>
						<input type="checkbox" id="check">
						<label for="check">自动登录</label>
						<a href="#">找回密码</a>
					</p>
					<input type="submit" value="登录">
					<p class="tuijian_title">亲，你可以选择以下快捷登录方式！</p>
				</form>
			</div>
			<div class="entry_right_bottom">
				<img src="{% static '/img/qq.png' %}">
			</div>
		</div>
		<div id="service">
			<div class="service_top"></div>
			<div class="service_bottom">
				<div class="QRCode"></div>
				<div class="service_list">
					<dl>
						<dt>购物指南</dt>
						<a href="#"><dd>新用户注册/激活</dd></a>
						<a href="#"><dd>如何订购</dd></a>
						<a href="#"><dd>常见问题</dd></a>
					</dl>
					<dl>
						<dt>会员中心</dt>
						<a href="#"><dd>会员权益</dd></a>
						<a href="#"><dd>美丽积分</dd></a>
						<a href="#"><dd>订单查询</dd></a>
						<a href="#"><dd>找回密码</dd></a>
					</dl>
					<dl>
						<dt>配送服务</dt>
						<a href="#"><dd>物流跟踪</dd></a>
						<a href="#"><dd>免运费政策</dd></a>
					</dl>
					<dl>
						<dt>支付说明</dt>
						<a href="#"><dd>货到付款</dd></a>
						<a href="#"><dd>在线支付</dd></a>
					</dl>
					<dl>
						<dt>售后服务</dt>
						<a href="#"><dd>退换货政策</dd></a>
						<a href="#"><dd>退换货流程</dd></a>
						<a href="#"><dd>安全与保密</dd></a>
					</dl>
				</div>
				<div class="telephone"></div>
			</div>
		</div>
		<div id="bottom">
			<ul class="bottom_link">
				<li><a href="#">商城首页</a></li>
				<li><a href="#">官网首页</a></li>
				<li><a href="#">供应商登录</a></li>
				<li><a href="#">供货联系</a></li>
				<li><a href="#">收藏我们</a></li>
				<li><a href="#">公司简介</a></li>
				<li><a href="#">媒体报道</a></li>
				<li><a href="#">嘉丽购招聘</a></li>
				<li><a href="#">官方微博</a></li>
				<li style="border-right: none;"><a href="#">合作网站：范游网</a></li>
			</ul>
			<p>嘉丽购物有限责任公司 Copyright 2010-2014 jialigou.All Rights Reserved</p>
			<p>国家广电总局批号：广局[2010] 278号湘ICP备10203162号-3</p>
			<a href="#"><img src="{% static '/img/pic.gif' %}" title="站长统计" class="pic"></a>
			<ul class="bottom_security">
				<li class="first"><img src="{% static '/img/kx.jpg' %}"></li>
				<li><a href="#"><img src="{% static '/img/360.jpg' %}"></a></li>
				<li><img src="{% static '/img/alipay_s.gif' %}"></li>
				<li><a href="#"><img src="{% static '/img/hn110_s.gif' %}"></a></li>
			</ul>
		</div>
    </body>
</html>